# Generated by Django 3.2.20 on 2023-08-31 18:34

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20230830_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='Ireland', max_length=10),
        ),
    ]
