# Generated by Django 3.2.20 on 2023-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cruelty_free',
            field=models.BooleanField(default=False),
        ),
    ]
